## bag of words (n_gram=(1,1)) by default

In [1]:
import numpy as np 
import pandas as pd

In [2]:
df=pd.DataFrame(
    {
        "text":["people watch campusx",
            "campusx watch campusx",
            "people write comment",
            "campusx write comment"],
        "output":[1,1,0,0]
    }
)

In [3]:
df.head()

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [5]:
bow=cv.fit_transform(df["text"])

In [6]:
# vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [7]:
len(cv.vocabulary_)

5

In [8]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]

### prediction

In [9]:
cv.transform(["campusx watch and write comment of campusx"]).toarray() # automatically ignores other non-vocabulary words

array([[2, 1, 0, 1, 1]])

## for n grams
- bigram n_gram range=(2,2)

In [10]:
import numpy as np 
import pandas as pd

In [11]:
df=pd.DataFrame(
    {
        "text":["people watch campusx",
            "campusx watch campusx",
            "people write comment",
            "campusx write comment"],
        "output":[1,1,0,0]
    }
)

In [12]:
df.head()

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2)) # for bigram, (3,3) for trigrams

In [14]:
bow=cv.fit_transform(df["text"])

In [15]:
# vocab
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}

In [16]:
len(cv.vocabulary_)

6

In [17]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]

## prediction

In [18]:
cv.transform(["campusx watch and write comment of campusx"]).toarray() # automatically ignores other non-vocabulary words

array([[1, 0, 0, 0, 0, 1]])

## TFIDF

In [19]:
import numpy as np
import pandas as pd

In [20]:
df=pd.DataFrame(
    {
        "text":["people watch campusx",
            "campusx watch campusx",
            "people write comment",
            "campusx write comment"],
        "output":[1,1,0,0]
    }
)

In [21]:
df

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df["text"]).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [26]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']